### PR TITLE
Production installation

### PR DESCRIPTION
**Pull request by JohannaOtt**
WGS-2537

### CODE REVIEW

**Review by Kate-Lyndegaard — COMMENTED** [review]
@JohannaOtt Your PR reverts changes made in this commit because someone could not see the point features due to size: https://github.com/wetransform-os/portrayal-repository/pull/8

The original SLD contained the sizes in the data specification, but were changed due to visibility issues. Do you have a reason for changing the size?

**Comment by JohannaOtt** [comment]
The size changes in [this commit](https://github.com/wetransform-os/portrayal-repository/pull/32/commits/2519051d910dd72b7bad79ef091deb21116b6c96) were only because I saw that they do not use the sizes provided in the Data specification. If we decided to deviate from that consciously, I am also ok with that. So far, I always thought we stick with the INSPIRE DS independent from how ugly/"useless" they are.
Same for the scale changes in [this commit](https://github.com/wetransform-os/portrayal-repository/pull/32/commits/fa38c618f6f4a043e282b66ac9535da6c4e37a26)

The Point filter was added because for example in [this dataset](https://haleconnect.com/features/#/map?request=https:%2F%2Fhaleconnect.com%2Fows%2Fservices%2Forg.292.9b6836e1-ed43-456d-b421-1ee2f87169d9_wms) is using the point style defined for the vector points of its polygons.

**Comment by Kate-Lyndegaard** [comment]
@JohannaOtt I think we really need to challenge ugly and useless INSPIRE DS rules. We have changed sizes before contrary to what is described in portrayal rules because otherwise no one can see the features. I adapted these, as well, because no one could see the features: https://github.com/wetransform-os/portrayal-repository/pull/13

**Review by Kate-Lyndegaard — APPROVED** [review]

**Comment by JohannaOtt** [comment]
> We have changed sizes before contrary to what is described in portrayal rules because otherwise no one can see the features

Ok then I would vote to also keep that as is for this case. I removed the respective commit from this PR

**Pull request merged**
